"""update music table 

Revision ID: 1f0f7939260d
Revises: a7f6d88a2ba5
Create Date: 2022-10-14 20:47:58.191597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f0f7939260d'
down_revision = 'a7f6d88a2ba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('musiques', 'songer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musiques', sa.Column('songer', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
