"""delete admin image table

Revision ID: a7f6d88a2ba5
Revises: ae17ce6823a1
Create Date: 2022-10-10 20:08:56.016598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f6d88a2ba5'
down_revision = 'ae17ce6823a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imageadmins')
    op.drop_column('adminsaccounts', 'number_phone')
    op.drop_column('adminsaccounts', 'is_active')
    op.drop_column('adminsaccounts', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adminsaccounts', sa.Column('code', sa.INTEGER(), nullable=False))
    op.add_column('adminsaccounts', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    op.add_column('adminsaccounts', sa.Column('number_phone', sa.INTEGER(), nullable=True))
    op.create_table('imageadmins',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('admin_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['adminsaccounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
